# Generated by Django 4.1 on 2022-08-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_register_delete_fformmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='MessageModel',
        ),
    ]
