# Generated by Django 4.1 on 2022-09-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_rename_register_messagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='address',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='phone',
        ),
    ]
