# Generated by Django 4.1 on 2022-09-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_educationmodel_heading_experiencemodel_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencemodel',
            name='technology',
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='institute',
            field=models.CharField(max_length=50),
        ),
    ]
