# Generated by Django 4.1 on 2022-09-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_remove_experiencemodel_technology_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencemodel',
            old_name='role',
            new_name='company',
        ),
    ]
