# Generated by Django 4.1.1 on 2022-09-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_rename_role_experiencemodel_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('heading2', models.CharField(blank=True, max_length=100, null=True)),
                ('heading3', models.CharField(blank=True, max_length=100, null=True)),
                ('heading4', models.CharField(blank=True, max_length=100, null=True)),
                ('heading5', models.CharField(blank=True, max_length=100, null=True)),
                ('heading6', models.CharField(blank=True, max_length=100, null=True)),
                ('heading7', models.CharField(blank=True, max_length=100, null=True)),
                ('conent', models.TextField()),
            ],
        ),
    ]
