# Generated by Django 4.1.1 on 2022-09-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_rename_conent_attractmodel_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractmodel',
            name='heading4',
        ),
        migrations.RemoveField(
            model_name='attractmodel',
            name='heading5',
        ),
        migrations.RemoveField(
            model_name='attractmodel',
            name='heading6',
        ),
        migrations.RemoveField(
            model_name='attractmodel',
            name='heading7',
        ),
    ]
