# Generated by Django 4.2.5 on 2023-10-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_remove_attractmodel_heading4_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttractModel',
            new_name='AboutModel',
        ),
    ]
