# Generated by Django 4.2.5 on 2023-10-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_alter_aboutmodel_banner1image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('heading2', models.CharField(blank=True, max_length=100, null=True)),
                ('heading3', models.CharField(blank=True, max_length=100, null=True)),
                ('bannerimage', models.ImageField(blank=True, null=True, upload_to='About/')),
            ],
        ),
    ]
