# Generated by Django 4.2.5 on 2023-10-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_bannermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='banner1image',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='banner2image',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='banner3image',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='heading2',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='heading3',
        ),
    ]
