# Generated by Django 4.1.1 on 2022-10-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='for_showcase',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
