# Generated by Django 4.1 on 2022-09-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_projectmodel_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('logo', models.ImageField(upload_to='social/')),
            ],
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
