# Generated by Django 4.1 on 2022-09-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_alter_projectmodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialModel',
        ),
    ]
