# Generated by Django 4.1.1 on 2022-09-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_achievementmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementmodel',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
