# Generated by Django 4.1.1 on 2022-09-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0008_achievementmodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='technology',
            field=models.CharField(max_length=200),
        ),
    ]
