# Generated by Django 4.2.5 on 2023-10-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0015_alter_achievementmodel_image_alter_extramodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Skills/')),
            ],
        ),
        migrations.CreateModel(
            name='ToolsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Tools/')),
            ],
        ),
        migrations.DeleteModel(
            name='AchievementModel',
        ),
        migrations.DeleteModel(
            name='ExtraModel',
        ),
    ]
