# Generated by Django 4.2.5 on 2023-10-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0016_skillsmodel_toolsmodel_delete_achievementmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='githubLink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
